[config]
version_check = false
caching = true

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.cava]
input_path = './templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = 'pkill -USR1 cava || true'

[templates.nvim]
input_path = './templates/nvim-colors.json'
output_path = "~/.config/matugen/themes/nvim-colors.json"
post_hook = 'pkill -SIGUSR1 nvim || true'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty || true'

[templates.starship]
input_path = './templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.vesktop]
input_path = './templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.fastfetch]
input_path = './templates/fastfetch-colors.jsonc'
output_path = '~/.config/fastfetch/config.jsonc'

[templates.niri]
input_path = './templates/niri-colors.kdl'
output_path = '~/.config/niri/_colors.kdl'
post_hook = 'niri msg action load-config-file'

[templates.quickshell]
input_path = './templates/quickshell.json'
output_path = '~/.local/state/quickshell/generated/colors.json'

[templates.gtk3]
input_path = './templates/gtk-3.0/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = './templates/gtk-4.0/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'
post_hook = '~/.config/matugen/scripts/gtk-hot-reload.sh'

[templates.kvantum_kvconfig]
input_path = './templates/kvantum/kvantum-colors.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

[templates.kvantum_svg]
input_path = './templates/kvantum/kvantum-colors.svg'
output_path = '~/.config/Kvantum/matugen/matugen.svg'

[templates.qt6ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.vscode-raw]
input_path = './templates/vscode-colors'
output_path = '~/.cache/matugen/vscode-colors'

[templates.vscode-json]
input_path = './templates/vscode-colors.json'
output_path = '~/.cache/matugen/vscode-colors.json'
