"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](primary)\
$os\
$username\
[ ](bg:secondary fg:primary)\
$directory\
[ ](bg:tertiary fg:secondary)\
$git_branch\
$git_status\
[ ](fg:tertiary bg:accent)\
$c\
$cpp\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[ ](fg:accent bg:container)\
$docker_context\
[ ](fg:container bg:surface)\
$time\
[  ](fg:surface)\
"""

palette = 'matugen'

[os]
style = "bg:primary fg:on-primary"
disabled = true # Disabled by default

[username]
show_always = true
style_user = "bg:primary fg:on-primary"
style_root = "bg:primary fg:on-primary"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:secondary fg:on-secondary"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = "  "

[c]
symbol = " "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[cpp]
symbol = "  "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[docker_context]
symbol = "  "
style = "bg:container"
format = '[[ $symbol $context ](fg:on-container bg:container)]($style)'

[elixir]
symbol = " "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[elm]
symbol = "  "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[git_branch]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol $branch ](fg:on-tertiary bg:tertiary)]($style)'

[git_status]
style = "bg:tertiary"
format = '[[($all_status$ahead_behind) ](fg:on-tertiary bg:tertiary)]($style)'

[golang]
symbol = " "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[gradle]
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[haskell]
symbol = " "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[java]
symbol = " "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[julia]
symbol = "  "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[nodejs]
symbol = ""
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[nim]
symbol = "󰆥 "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[rust]
symbol = ""
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[scala]
symbol = " "
style = "bg:accent"
format = '[[ $symbol ($version) ](fg:on-accent bg:accent)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:surface"
format = '[[  ♥ $time ](fg:on-surface bg:surface)]($style)'

[palettes.matugen]

primary = '#c1cd7d'
on-primary = '#2d3400'
primary-container = '#424b07'
on-primary-container = '#ddea96'

secondary = '#c6c9a7'
on-secondary = '#2f321a'
secondary-container = '#45492f'
on-secondary-container = '#e2e5c2'

tertiary = '#a2d0c3'
on-tertiary = '#05372e'
tertiary-container = '#224e44'
on-tertiary-container = '#bdecde'

error = '#ffb4ab'
on-error = '#690005'
error-container = '#93000a'
on-error-container = '#ffdad6'

surface = '#13140d'
on-surface = '#e4e3d6'
surface-variant = '#47483b'
on-surface-variant = '#c8c7b7'

container = '#1f2018'
on-container = '#e4e3d6'
container-high = '#2a2b22'
container-low = '#1b1c15'

accent = '#a2d0c3'
on-accent = '#05372e'

success = '#c1cd7d'

outline = '#919283'
outline-variant = '#47483b'
