[CUSTOM]
# Alternative color mode (default is 0), some images return more than one color, this will use either the matched or last color
# Default is 0
ncolor = 0

# Light scheme icons theme
#iconslight = OneUI-light
iconslight = Tela-circle-light

# Dark scheme icons theme
iconsdark = Tela-circle-dark

# Use pywal to theme other programs using Material You colors
pywal=False

# The amount of perceptible color for backgrounds in dark mode
# A number between 0 and 4.0 (limited for accessibility purposes)
# Defaults to 1 if not set
#light_blend_multiplier = 1.0

# The amount of perceptible color for backgrounds in dark mode
# A number between 0 and 4.0 (limited for accessibility purposes)
# Defaults to 1 if not set
#dark_blend_multiplier = 1.0

# A script/command that will be executed on start or wallpaper/dark/light/settings change
# example below using https://github.com/vlevit/notify-send.sh to send a desktop notification:
#on_change_hook = notify-send.sh "kde-material-you-colors" "This is a test" -t 2000

# Scheme Variant
# Changes between Material You scheme variants (0-8)
# 0 = Content
# 1 = Expressive
# 2 = Fidelity
# 3 = Monochrome
# 4 = Neutral
# 5 = TonalSpot
# 6 = Vibrant
# 7 = Rainbow
# 8 = FruitSalad
# Default is 5
scheme_variant = 5

# Colorfulness
chroma_multiplier = 1

# Brightness
# An integer between 0.5 and 1.5
tone_multiplier = 1
