"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](primary)\
$os\
$username\
[](bg:secondary fg:primary)\
$directory\
[](bg:tertiary fg:secondary)\
$git_branch\
$git_status\
[](bg:accent fg:tertiary)\
$c\
$cpp\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$vala\
[](bg:container fg:accent)\
$docker_context\
[](bg:surface fg:container)\
$time\
[ ](fg:surface)\
$character"""

palette = 'matugen'

[os]
disabled = false
style = "bg:primary fg:on-primary"
format = "[ $symbol]($style)"

[os.symbols]
Arch = "󰣇 "

[username]
show_always = true
style_user = "bg:primary fg:on-primary"
style_root = "bg:primary fg:on-primary"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:secondary fg:on-secondary"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = "  "

[git_branch]
symbol = ""
style = "bg:tertiary fg:on-tertiary"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:tertiary fg:on-tertiary"
format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = " "
style = "bg:accent fg:on-accent"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = "  "
style = "bg:accent fg:on-accent"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:accent fg:on-accent"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "bg:accent fg:on-accent"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "  "
style = "bg:accent fg:on-accent"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:accent fg:on-accent"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:accent fg:on-accent"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:accent fg:on-accent"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "  "
style = "bg:accent fg:on-accent"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:accent fg:on-accent"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:accent fg:on-accent"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:accent fg:on-accent"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:accent fg:on-accent"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "  "
style = "bg:container fg:on-container"
format = '[ $symbol $context ]($style)'

[time]
disabled = true
time_format = "%R"
style = "bg:surface fg:on-surface"
format = '[ ♥ $time ]($style)'

[character]
success_symbol = "[❯](fg:success)"
error_symbol = "[❯](fg:error)"

[palettes.matugen]
primary = '{{colors.primary.default.hex}}'
on-primary = '{{colors.on_primary.default.hex}}'
primary-container = '{{colors.primary_container.default.hex}}'
on-primary-container = '{{colors.on_primary_container.default.hex}}'

secondary = '{{colors.secondary.default.hex}}'
on-secondary = '{{colors.on_secondary.default.hex}}'
secondary-container = '{{colors.secondary_container.default.hex}}'
on-secondary-container = '{{colors.on_secondary_container.default.hex}}'

tertiary = '{{colors.tertiary.default.hex}}'
on-tertiary = '{{colors.on_tertiary.default.hex}}'
tertiary-container = '{{colors.tertiary_container.default.hex}}'
on-tertiary-container = '{{colors.on_tertiary_container.default.hex}}'

error = '{{colors.error.default.hex}}'
on-error = '{{colors.on_error.default.hex}}'
error-container = '{{colors.error_container.default.hex}}'
on-error-container = '{{colors.on_error_container.default.hex}}'

surface = '{{colors.surface.default.hex}}'
on-surface = '{{colors.on_surface.default.hex}}'
surface-variant = '{{colors.surface_variant.default.hex}}'
on-surface-variant = '{{colors.on_surface_variant.default.hex}}'

container = '{{colors.surface_container.default.hex}}'
on-container = '{{colors.on_surface.default.hex}}'
container-high = '{{colors.surface_container_high.default.hex}}'
container-low = '{{colors.surface_container_low.default.hex}}'

accent = '{{colors.tertiary.default.hex}}'
on-accent = '{{colors.on_tertiary.default.hex}}'

success = '{{colors.primary.default.hex}}'

outline = '{{colors.outline.default.hex}}'
outline-variant = '{{colors.outline_variant.default.hex}}'
